### ISSUE TITLE
Can you add toggle state to encoder button?

### ISSUE THREAD

**Issue by nosuper** [benkuper/XTouch-Mini-Chataigne-module#1]
I would like to have a toggle state for encoders button. Can you please help?

**Comment by benkuper** [comment]
What do you need it for ?
The normal buttons actually have 2 visual state in hardware : (light on/off), but the encoder don't. It would be a virtual toggle state that can't be directly represented on the hardware.
You can easily use toggles for the encoder button using actions with the toggle mode in a Standard Condition.

**Comment by nosuper** [comment]
I'm trying to control voice meter using virtual midi. and I want Full Feedback Midi which means when we press the button on UI, the midi also has feedback. So the problem is the button on UI is a toggle and I can't set the velocity for the encoder button to hold the toggle state.

Btw I don't understand your instruction above. Can you attach a screenshot? I'm really new to chataigne 👯

**Comment by benkuper** [comment]
![image](https://github.com/benkuper/XTouch-Mini-Chataigne-module/assets/1291595/e4f57bb1-f2e3-4f9a-a411-46f8c338add4)

**Comment by benkuper** [comment]
If you need to hold a toggle state information, you can use custom variables as well

**Comment by nosuper** [comment]
Thank you so much
